Fix unused variable warning in parseQemuSensorEventLocked
Bug: 436273434

device/generic/goldfish/hals/sensors/multihal_sensors_qemu.cpp:356:28: error: variable 'values' set but not used [-Werror,-Wunused-but-set-variable]
  356 |     } else if (const char* values = testPrefix(buf, end, "sync", ':')) {
      |                            ^
1 error generated.

Change-Id: I97005012ddf22c47a1cc2ba298b7d8dd6283301b